set background=dark
colors molokai

" Gutter color default is annoying. Make it blend in.
hi SignColumn guibg=NONE

" Command-Shift-F is fullscreen.
nmap <D-F> :set fullscreen!<CR>

set guifont=Inconsolata:h14 
set columns=120 lines=46
set guicursor+=a:blinkon0
set guioptions=aigm
set mousemodel=popup
set scrolloff=6
set sidescrolloff=6
set visualbell
set errorbells
set nocursorline
set nonumber

" Now load specifics to this machine.
source ~/.gvimlocal
